Repository Step3-kakao-tech-campus/Team6_BE, pull requests merged in 2023-11, with the labels that each got.

#62 Refactor : 리뷰 파일 삭제 로직 변경
  src/main/java/com/example/tripKo/domain/place/api/ReviewController.java
  src/main/java/com/example/tripKo/domain/place/application/ReviewService.java
  src/main/java/com/example/tripKo/domain/place/entity/Review.java
  src/main/java/com/example/tripKo/domain/place/entity/ReviewHasFile.java
Labels: refactor

#71 Fix : 회원가입 유효성 검사 수정
  src/main/java/com/example/tripKo/domain/member/api/MemberController.java
  src/test/java/com/example/tripKo/domain/member/api/MemberControllerTest.java
Labels: bug

#76 Feature : home api 구현
  src/main/java/com/example/tripKo/domain/place/api/ContentsController.java
  src/main/java/com/example/tripKo/domain/place/application/ContentsService.java
  src/main/java/com/example/tripKo/domain/place/dto/response/info/HomeResponse.java
  src/main/java/com/example/tripKo/domain/place/dto/response/info/TouristSpotResponse.java
Labels: feature

#85 Refactor : 에러코드 수정 및 상태코드 수정
  src/main/java/com/example/tripKo/_core/errors/ErrorCode.java
  src/main/java/com/example/tripKo/_core/errors/exception/BusinessException.java
  src/main/java/com/example/tripKo/domain/food/application/FoodService.java
  src/main/java/com/example/tripKo/domain/member/api/MemberController.java
  src/main/java/com/example/tripKo/domain/member/application/MemberService.java
  src/main/java/com/example/tripKo/domain/member/application/WishlistService.java
  src/main/java/com/example/tripKo/domain/place/application/ContentsService.java
  src/main/java/com/example/tripKo/domain/place/application/PlaceService.java
  src/main/java/com/example/tripKo/domain/place/application/convenience/ValidContentsService.java
  src/test/java/com/example/tripKo/domain/member/application/MemberServiceTest.java
Labels: refactor

#86 Feat: S3 도입
  .gitignore
  build.gradle
  src/main/java/com/example/tripKo/_core/S3/ImageS3Service.java
  src/main/java/com/example/tripKo/_core/S3/S3Config.java
  src/main/java/com/example/tripKo/_core/errors/ErrorCode.java
  src/main/java/com/example/tripKo/_core/security/SecurityConfig.java
  src/main/java/com/example/tripKo/_core/utils/TestData.java
  src/main/java/com/example/tripKo/domain/file/entity/File.java
  src/main/java/com/example/tripKo/domain/food/dto/response/FoodDetailsResponse.java
  src/main/java/com/example/tripKo/domain/food/dto/response/FoodResponse.java
  src/main/java/com/example/tripKo/domain/member/application/MemberService.java
  src/main/java/com/example/tripKo/domain/member/dto/response/FestivalReservationResponse.java
  src/main/java/com/example/tripKo/domain/member/dto/response/RestaurantReservationResponse.java
  src/main/java/com/example/tripKo/domain/member/dto/response/review/ReviewsResponse.java
  src/main/java/com/example/tripKo/domain/member/dto/response/userInfo/UserInfoResponse.java
  src/main/java/com/example/tripKo/domain/member/dto/response/wishlist/WishlistResponse.java
  src/main/java/com/example/tripKo/domain/place/api/ContentsController.java
  src/main/java/com/example/tripKo/domain/place/application/ReviewService.java
  src/main/java/com/example/tripKo/domain/place/dto/request/ReviewUpdateRequest.java
  src/main/java/com/example/tripKo/domain/place/dto/response/info/FestivalResponse.java
  src/main/java/com/example/tripKo/domain/place/dto/response/info/RestaurantResponse.java
  src/main/java/com/example/tripKo/domain/place/dto/response/info/TouristSpotResponse.java
  src/main/java/com/example/tripKo/domain/place/dto/response/review/ReviewsResponse.java
  src/main/java/com/example/tripKo/domain/place/dto/response/search/PlaceFestivalResponse.java
  src/main/java/com/example/tripKo/domain/place/dto/response/search/PlaceRestaurantResponse.java
  src/main/java/com/example/tripKo/domain/place/dto/response/search/PlaceTouristSpotResponse.java
  src/main/java/com/example/tripKo/domain/place/entity/ReviewHasFile.java
  src/main/resources/application.properties
  src/test/java/com/example/tripKo/domain/file/FileTestHelper.java
Labels: feature

#66 부산대_6조_tripKo_9주차
  .gitignore
  build.gradle
  src/docs/asciidoc/member/member.adoc
  src/main/java/com/example/tripKo/_core/security/JwtProvider.java
  src/main/java/com/example/tripKo/_core/security/RedisConfig.java
  src/main/java/com/example/tripKo/_core/security/SecurityConfig.java
  src/main/java/com/example/tripKo/_core/security/data/CustomOAuth2UserService.java
  src/main/java/com/example/tripKo/_core/security/data/JwtToken.java
  src/main/java/com/example/tripKo/_core/security/data/JwtType.java
  src/main/java/com/example/tripKo/_core/security/data/JwtUserDetails.java
  src/main/java/com/example/tripKo/_core/security/data/JwtUserDetailsService.java
  src/main/java/com/example/tripKo/_core/security/data/JwtValidationType.java
  src/main/java/com/example/tripKo/_core/security/data/OAuth2SuccessHandler.java
  src/main/java/com/example/tripKo/_core/security/data/OAuthAttributes.java
  src/main/java/com/example/tripKo/_core/security/data/RefreshToken.java
  src/main/java/com/example/tripKo/_core/security/data/TokenValidationDTO.java
  src/main/java/com/example/tripKo/_core/security/filter/JwtAuthFilter.java
  src/main/java/com/example/tripKo/_core/security/filter/RefreshTokenFilter.java
  src/main/java/com/example/tripKo/_core/utils/RedisUtil.java
  src/main/java/com/example/tripKo/_core/utils/TestData.java
  src/main/java/com/example/tripKo/domain/food/dao/FoodContentsHadFileRepository.java
  src/main/java/com/example/tripKo/domain/food/dao/FoodContentsRepository.java
  src/main/java/com/example/tripKo/domain/food/dao/FoodHasFileRepository.java
  src/main/java/com/example/tripKo/domain/food/dto/response/FoodDetailsResponse.java
  src/main/java/com/example/tripKo/domain/food/entity/Food.java
  src/main/java/com/example/tripKo/domain/food/entity/FoodContents.java
  src/main/java/com/example/tripKo/domain/food/entity/FoodHasFile.java
  src/main/java/com/example/tripKo/domain/member/api/MemberController.java
  src/main/java/com/example/tripKo/domain/member/application/MemberService.java
  src/main/java/com/example/tripKo/domain/member/application/convenience/CheckDuplicateService.java
  src/main/java/com/example/tripKo/domain/member/dao/MemberRepository.java
  src/main/java/com/example/tripKo/domain/member/dto/request/MemberRequest.java
  src/main/java/com/example/tripKo/domain/member/dto/request/SignInRequest.java
  src/main/java/com/example/tripKo/domain/member/dto/request/SignUpRequest.java
  src/main/java/com/example/tripKo/domain/member/entity/Member.java
  src/main/java/com/example/tripKo/domain/place/api/ReviewController.java
  src/main/java/com/example/tripKo/domain/place/application/ReviewService.java
  src/main/java/com/example/tripKo/domain/place/entity/Review.java
  src/main/java/com/example/tripKo/domain/place/entity/ReviewHasFile.java
  src/main/resources/application.properties
  src/test/java/com/example/tripKo/domain/member/api/MemberControllerTest.java
  src/test/java/com/example/tripKo/domain/member/application/MemberServiceTest.java
  src/test/java/com/example/tripKo/domain/security/JwtProviderTest.java
Labels: Review Request
